### ISSUE TITLE
本人用QT写了一个农历库项目，其中农历算法使用了你的项目。

### ISSUE THREAD

**Issue by KangLin** [yuangu/sxtwl_cpp#12]
本人用QT写了一个农历库项目，其中农历算法使用了你的项目。
本人项目位置：https://github.com/KangLin/LunarCalendar

**Comment by xros** [comment]
看上去不错。谁能来开发个手机app版本的呢？有分享的吗
不过貌似Qt可以直接生成app版本。我用的是PyQt 不过好像做不到你这样的程度

**Comment by KangLin** [comment]
本项目已支持ANDROID版本，你git pull最新版本，直接用Qt编译即可。稍后，v0.02版本，我会提供自动化编译的APK包供下载。

**Comment by TSG9876** [comment]
可用Android NDK  加简单的jni C++ callback 实现所有农历对算，无需源码修改，便可在App应用

**Comment by yuangu** [comment]
升级了一下接口，欢迎使用新版的sxtwl

**Comment by KangLin** [comment]
升级文档？

**Comment by yuangu** [comment]
接口和文档都升级了
