### ISSUE TITLE
性能优化建议

### ISSUE THREAD

**Issue by KangLin** [yuangu/sxtwl_cpp#13]
本人机器配置：
CPU: Intel(R) Celeron(R) CPU G1820 @2.70GH
内存：4G
操作系统：Windows10 专业版（1809）

测试性能：
getDayBySolar 函数平均调用时间为40ms。一个月日历一般为 40天左右。所以40*40=1600S

结论：
在更低配置的机器上（例如：手机），性能不能满足业务需求。单次性能有待提高。

优化建议：
1. 编译器指令优化，使用浮点编译选项。
2. 源码汇编指令集优化：根据不同CPU平台，使用相应的汇编浮点指令。
3. 源码级程序结构优化：加入缓存，计算过的日期，可直接从缓存中读取出来，不需要重复计算。这个优化是重点。在日历型应用中，经常是连续的日历读取。所以本优化会明显提升性能。注意缓存大小可以由用户设置。
5. 提供缓存表工具，用于指定范围内的时间生成表，并保存到文件或数据，程序支持查表方式读取日期。

**Comment by KangLin** [comment]
我在提交 c94b227 中打印出了时间信息，你可以用此代码进行测试。

git clone https://github.com/KangLin/LunarCalendar.git 
git checkout -b  c94b227 c94b227

**Comment by yuangu** [comment]
嗯 ，我下一步着手优化一下性能问题

**Comment by yuangu** [comment]
兄弟，你试一下Month yueLiCalc(int By, uint8_t Bm) ;

**Comment by KangLin** [comment]
缓存我已写好，你可以参考：
https://github.com/KangLin/LunarCalendar/blob/master/Src/LunarTable.h





在 2019-04-20 22:55:07，"yuangu" <notifications@github.com> 写道：


嗯 ，我下一步着手优化一下性能问题

**Comment by yuangu** [comment]
> 缓存我已写好，你可以参考： https://github.com/KangLin/LunarCalendar/blob/master/Src/LunarTable.h 在 2019-04-20 22:55:07，"yuangu" <notifications@github.com> 写道： 嗯 ，我下一步着手优化一下性能问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

嗯，我尝试了浮点编译选项，好像没有什么卵用。关于汇编浮点指令，有没有资料。另外，我发现的接口还是太重了，没有分细点，有很多东西其实有人是不需要的，比如节气信息等

**Comment by KangLin** [comment]
是的，细分一下更好！节气信息还是需要的，但可以单独分出来。
可以减少不必要的计算
阳历转农历中，没必要算儒略日。就要算，也只要是整数日就行了。不要时间。

**Comment by KangLin** [comment]
浮点编译选项，应该是有一定做用的，尤其是在手机上。
PC汇编浮点编译器：masm,yasm
浮点指令集：https://blog.csdn.net/gaogyc/article/details/50625587
《ARM 指令集》IEEE浮点指令：http://www.mz6.net/news/2014-02-08/1081_14.html
其更加具体的指令，请查看相应编译器的帮助手册。

**Comment by KangLin** [comment]
在我机器上从1970年到2120年，用了将近20分钟，你可以写个类似的测试程序，测试下浮点编译选项，看看能减少多少时间。

**Comment by yuangu** [comment]
我开了一个新的分支，
1、复写原来的代码的时候我发现有位置做了递归计算，一直算到每日所属月的第一天。嗯，还有节气的运算也有类似。这个我昨天 晚上只改了一处。我考虑去掉月相。
2、增加了一个新类SXDay，这个类就是把业务拆分的。

下一步，原有方式我还要保留，里头做些优化。在SXDay里把一些东西改成有利于理解的，比如获取阴历，不使用索引。年直接加上1984。

**Comment by TSG9876** [comment]
https://github.com/yuangu/sxtwl_cpp/issues/12#issuecomment-592040414，节气可一次回调，不必一对一转换，实现快速计貧。

**Comment by yuangu** [comment]
已做优化
