### ISSUE TITLE
儒略日有问题

### ISSUE THREAD

**Issue by KangLin** [yuangu/sxtwl_cpp#15]
Day中的儒略日计算与QDate.toJulianDay() 的值不同？

**Comment by yuangu** [comment]
加上 J2000对一下看

**Comment by yuangu** [comment]
兄弟，问题解决了么？我先把issue关了哈。如果还有问题，你就再提一个新的issue，或者加我微信聊。另外，最近我升级了sxtwl，接口更好用点。
