### ISSUE TITLE
AttributeError: 'Lunar' object has no attribute 'siZhu2Year'

### ISSUE THREAD

**Issue by hook923** [yuangu/sxtwl_cpp#19]
您好，sxtwl提示没有'siZhu2Year'，是什么原因呢？
另外，能否在python中获取某一时间段的所有节气(精确到秒)？
谢谢

**Comment by yuangu** [comment]
兄弟，问题解决了没？我把sxtwl升级了，重新设计了一下接口，更好用点。你可以对比一下时间的问题。如果还有问题，你就再提交一个issue或者加我微信沟通。
