### ISSUE TITLE
Python 下jqmc返回值问题

### ISSUE THREAD

**Issue by eleveni386** [yuangu/sxtwl_cpp#21]
jqmc = ["冬至", "小寒", "大寒", "立春", "雨水", "惊蛰", "春分", "清明", "谷雨", "立夏", "小满", "芒种", "夏至", "小暑", "大暑", "立秋", "处暑","白露", "秋分", "寒露", "霜降", "立冬", "小雪", "大雪"]

lunar.getDayBySolar(2019,12,1).jqmc # 此时返回 0 , 难道2019-12-1 的节气是 冬至? 

所以想问问作者大大. 如果当天并不是某个节气时. jqmc返回的是什么?

**Comment by NCEPUYTL** [comment]
你好这个问题解决了吗

**Comment by eleveni386** [comment]
@NCEPUYTL 已经解决. 使用jqsj来判断, 如果当日存在节气, jqsj将返回节气的开始时间, 如果不存在jqsj 将返回空. jqmc方法在当前版本下,无法明确的告诉你是否不存在节气

**Comment by yuangu** [comment]
用新版本试试看，接口更加友好点。另，获取 当天节气需要判断当天是否有节气。如还有问题，请提交新的issue，或者加微信沟通。
