### ISSUE TITLE
python 3.7.6_1下出现'Day' object has no attribute 'cur_dx'

### ISSUE THREAD

**Issue by mfyang** [yuangu/sxtwl_cpp#22]
` File "/usr/local/lib/python3.7/site-packages/sxtwl.py", line 306, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Day, name)
  File "/usr/local/lib/python3.7/site-packages/sxtwl.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Day' object has no attribute 'cur_dx'`

**Comment by mfyang** [comment]
3.6.1下是正常的

**Comment by yuangu** [comment]
用新版本的sxtwl吧，接口相对会更加友好点。pip默认提供全平台的wheel包。如果还有问题请提交新的issue或者加微沟通。
