### ISSUE TITLE
农历跨年时，农历年显示不对

### ISSUE THREAD

**Issue by anningwang** [yuangu/sxtwl_cpp#24]
例如 2020-1-25日 是农历 春节（正月初一），春节后为鼠年，应该为
庚子年 【鼠年】
上一年是 己亥年 【猪年】， 到了春节还是显示 乙亥年

使用代码：
print(Gan[day.Lyear2.tg], Zhi[day.Lyear2.dz], "年", Gan[day.Lmonth2.tg], Zhi[day.Lmonth2.dz], "月",\
        Gan[day.Lday2.tg], Zhi[day.Lday2.dz], "日")

**Comment by mfyang** [comment]
立春之后才交换节气的，不是正月初一

**Comment by yuangu** [comment]
等新的日历库发布，这个我做了一个选项参数。有些人确实是以正月初一为准的，命理人是以立春为准的。不做争论，请期待新版本日历…………

**Comment by yuangu** [comment]
已更新，如还有问题，请提交新的issue或者加微信共同讨论
