### ISSUE TITLE
交节气的时间计算可否准确到秒？

### ISSUE THREAD

**Issue by mfyang** [yuangu/sxtwl_cpp#26]
交节气的时间，决定农历月是否更换。

比如1898年03月05日　20时49分51秒　　进入惊蛰，因此这一天的20时49分51秒之前其实算是甲寅月，之后才算乙卯月。

**Comment by yuangu** [comment]
对，按你的意思确实是这样子的，日历库给了具体的节气JD时间，并且日历库给了JD库的转换时间，可以精确到0.xxx毫秒，我自己是做四舍五入来使用的。
