### ISSUE TITLE
是否可以以增加干支反推公历的功能

### ISSUE THREAD

**Issue by maginn** [yuangu/sxtwl_cpp#3]
这是一个非常好的工具，可以实现命理当中的排盘的基础功能。
是否可以增加 公国干支反推公历具体时间的功能呢？

谢谢！

**Comment by yuangu** [comment]
干支反推功能这个实现比较简单，我把这块放到八字模块了

**Comment by yuangu** [comment]
这个主要是日历模块，八字模块提供反推功能。
