### ISSUE TITLE
阳历对应阴历bug

### ISSUE THREAD

**Issue by hyalone** [yuangu/sxtwl_cpp#33]
>>> sxtwl.fromSolar(1582,10,14).getLunarDay()
28
>>> sxtwl.fromSolar(1582,10,15).getLunarDay()
19
阳历是连着的两天，转换成阴历差了9天

**Comment by ZZLinvec** [comment]
公元 1582 年 10 月 5 日 含 至 10 月 14 日很特殊的日子

**Comment by hyalone** [comment]
ok, i see
