### ISSUE TITLE
是否可以支持datetime类型的日期转换

### ISSUE THREAD

**Issue by childrenbody** [yuangu/sxtwl_cpp#7]
能否将公历的datetime.datetime(2019, 1, 11)直接转换为阴历的datetime.datetime(2018, 12, 6)

**Comment by maginn** [comment]
day=lunar.getDayBySolar(1977,12,1)
print(u"公历:", day.y, u"年", day.m, u"月", day.d, u"日")
print(u"阴历:", 1984+day.Lyear0, u"年",DictClass.ymc[day.Lmc], u"月", DictClass.rmc[day.Ldi], u"日")
print("---666---")

day1=lunar.getDayByLunar(1977,10,21)
print(u"公历:", day1.y, u"年", day1.m, u"月", day1.d, u"日")
print(u"阴历:", 1984+day1.Lyear0, u"年",DictClass.ymc[day1.Lmc], u"月", DictClass.rmc[day1.Ldi], u"日")



ppday=lunar.getDayBySolar(year, mouth, day)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~")
daytg=ppday.Lday2.tg

print(u"公历:", ppday.y, u"年", ppday.m, u"月", ppday.d, u"日")
print(u"阴历:", 1984 + ppday.Lyear0, u"年", DictClass.ymc[ppday.Lmc], u"月", DictClass.rmc[ppday.Ldi], u"日")




在 2019-01-11 17:06:38，"childrenbody" <notifications@github.com> 写道：


能否将公历的datetime.datetime(2019, 1, 11)直接转换为阴历的datetime.datetime(2018, 12, 6)

**Comment by yuangu** [comment]
你可以自己封装一下，这个库除了提供阴历转阳历等一些工作以外，还有天干地支，节气的运算
